[versions]
# https://github.com/vaadin/platform/tags
vaadin = "25.0.4"
vaadin_next = "25.1.0-alpha3"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.17"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jetbrains-annotations = "org.jetbrains:annotations:24.1.0"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
vaadin-dev = { module = "com.vaadin:vaadin-dev", version.ref = "vaadin" }
vaadinnext-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin_next" }
kaributesting = "com.github.mvysny.kaributesting:karibu-testing-v24:2.6.2"
junit = "org.junit.jupiter:junit-jupiter-engine:6.0.1"
vaadinboot = "com.github.mvysny.vaadin-boot:vaadin-boot:13.6"
# https://github.com/mvysny/karibu-tools/tags
kaributools = "com.github.mvysny.karibu-tools:karibu-tools-23:0.27"
# https://repo1.maven.org/maven2/org/hibernate/validator/hibernate-validator/
hibernate-validator = "org.hibernate.validator:hibernate-validator:9.1.0.Final"
jakarta-el = "org.glassfish:jakarta.el:4.0.2"
# https://mvnrepository.com/artifact/org.jetbrains.kotlin-wrappers/kotlin-css-jvm
kotlin-css-jvm = "org.jetbrains.kotlin-wrappers:kotlin-css-jvm:2026.1.3"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
